FROM jekyll/jekyll:latest
COPY web/_site /var/www/public
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/html/404.html /usr/share/nginx/html/404.html
CMD jekyll build

FROM nginx:latest
CMD nginx -g 'daemon off;'