FROM jekyll/jekyll:latest AS builder

CMD jekyll build

FROM nginx:latest

COPY --from=builder web/_site /var/www/public
COPY --from=builder nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder nginx/html/404.html /usr/share/nginx/html/404.html

CMD nginx -g 'daemon off;'