highlighter: pygments

permalink: pretty

title: Rock n' Prog
email: fabienroy28@gmail.com
tagline: "It's not code : it's monospaced prose."
description: My personal blog for programming and dev-related things.

baseurl: /
url: "https://rocknprog.com"

twitter_username: ExiledNarwal28
github_username: ExiledNarwal28

sass:
  sass_dir: public/css

plugins:
  - jekyll-redirect-from

exclude:
  - Rakefile
  - static.json
