highlighter: pygments

permalink: pretty

title: Rock n' Prog
email: fabienroy28@gmail.com
tagline: "It's not code : it's monospaced prose."
description: My personal blog for programming and dev-related things.

baseurl: /
url: "" # TODO : The base hostname & protocol for your site, e.g. http://example.com

twitter_username: ExiledNarwal28
github_username: ExiledNarwal28

sass:
  sass_dir: public/css

# TODO : Find a better way to redirect than in index.html
exclude:
  - Rakefile