title: Rock n' Prog
email: fabienroy28@gmail.com
description: My personal blog for programming and dev-related things.
baseurl: ""
url: "" # TODO : The base hostname & protocol for your site, e.g. http://example.com
twitter_username: ExiledNarwal28
github_username:  ExiledNarwal28

theme: minima
plugins:
  - jekyll-feed

# TODO : Check if I exclude things
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
